server.port=8089
spring.application.name=envios
spring.datasource.url=jdbc:mysql://localhost:3306/envios_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true