server.port=8086
spring.application.name=notificaciones

# Eureka
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka 
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
# ============================================================
# Registro en Eureka
# ============================================================
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=127.0.0.1
eureka.instance.instance-id=127.0.0.1:${spring.application.name}:${server.port}